// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/mac/Projects/GitHub/dumi-demo/node_modules/dumi/theme-default/builtins/Table/index.js';
